"""create pokemons table

Revision ID: ab4cbc29a03b
Revises: 
Create Date: 2026-07-14 21:57:04.999153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4cbc29a03b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('types', sa.JSON(), nullable=False),
    sa.Column('front_sprite', sa.String(), nullable=False),
    sa.Column('back_sprite', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemons_name'), 'pokemons', ['name'], unique=False)
    op.create_index(op.f('ix_pokemons_pokemon_id'), 'pokemons', ['pokemon_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemons_pokemon_id'), table_name='pokemons')
    op.drop_index(op.f('ix_pokemons_name'), table_name='pokemons')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
