# Pipeline do Logstash
input {
  file {
    path => "/app/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "pokemon-api-logs"
  }

  stdout {
    codec => rubydebug
  }
}